# pytest.ini
[pytest]
addopts = -vs --tb=short --strict-markers --alluredir=automation/reports/allure-results --clean-alluredir --maxfail=5
testpaths = automation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: 冒烟测试
    regression: 回归测试
    web: Web 测试
    edge: 边界测试

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S